import { StyleSheet } from 'react-native'

export const CustomDateStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  contentContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: Platform.OS === 'ios' ? 22 : 15,
    paddingHorizontal: 30,
  },
  whiteBackground: {
    backgroundColor: 'white',
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    padding: 20,
    alignItems: 'center',
  },
  dateButtonContainer: {
    backgroundColor: 'white',
    borderRadius: 25,
    marginBottom: 20,
  },
  dateButton: {
    flexDirection: 'row',
    backgroundColor: '#026CD2',
    borderWidth: 1,
    borderColor: '#026CD2',
    paddingVertical: 25,
    paddingHorizontal: 110,
    shadowColor: '#000',
    borderRadius: 20,
    alignItems: 'center',
    elevation: 5,
    marginBottom: 10,
  },
  buttonText: {
    color: '#144D56',
    textAlign: 'center',
    fontFamily: 'PoppinsRegular',
    fontSize: 18,
  },
  showMoreButton: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: 'white',
    paddingVertical: Platform.OS === 'ios' ? 15 : 13,
    paddingHorizontal: Platform.OS === 'ios' ? 20 : 25,
    borderRadius: 20,
    marginTop: 15,
    marginBottom: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  showMoreButtonText: {
    color: '#144D56',
    textAlign: 'center',
    fontFamily: 'PoppinsRegular',
    fontSize: Platform.OS === 'ios' ? 15 : 13,
  },
})
